### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by rowthan** [xingbofeng/wx-audio#1]
因为没有做过微信小程序，所以运行时并没有用于微信小程序。
只是把该项目当做一个node项目运行起来了，但是运行报错。第一个是let语法不兼容，可能是node版本问题吧，改成var后不报错了，这里建议在readme文档或者package.json中说明一下版本依赖问题。
另外有一个错报在POSTHTTP.js中，
```
const {
          name,
          audio: musicUrl,
          page,
          album: {
            name: musicName,
            picUrl,
          },
          artists: [{
            name: singer,
          }],
        } = JSON.parse(body).result.songs[0];
```
![image](https://cloud.githubusercontent.com/assets/12638456/22454664/928943c2-e7c2-11e6-90d8-d49f598f0700.png)

**Comment by xingbofeng** [comment]
您好，感谢您的关注！
`let`与`const`及`对象解构`均为`es6`的语法，依赖的版本为`node v7.1.0`，建议升级node版本
升级方法为：
```shell
npm install -g n
n stable
```
