### ISSUE TITLE
为什么要加一层node来？直接请求网易云的API不是更简单？

### ISSUE THREAD

**Issue by GitGump** [xingbofeng/wx-audio#2]
NodeJS在这里有什么作用不太明白，请教一下。

**Comment by xingbofeng** [comment]
您好，添加node层的目的主要是在后端格式化数据，因为请求的API一些数据是多余的。
更多在开发的情况下可以自建node端解决跨域问题等。
您可以上网搜索一些微服务、中间层相关的文章阅读。
